const ProductList = [
  {
    id: 1,
    name: "Ultimate 3D Bluetooth Speaker",
    imgSrc: require( '../../static/images/product/product-1/product-1.jpg' ),
    oldPrice: "59.00",
    price: "49.00",
    link: "#",
    enableAddToCart: false,
    quantity: 0,
    totalQuantity: 90,
    isFavorite: false,
    checked: false,
    isComplete: false,
  },
  {
    id: 2,
    name: "Ultimate 3D Bluetooth Speaker",
    imgSrc: require( '../../static/images/product/product-1/product-2.jpg' ),
    oldPrice: "19.00",
    price: "9.00",
    link: "#",
    enableAddToCart: false,
    quantity: 0,
    totalQuantity: 100,
    isFavorite: false,
    checked: false,
    isComplete: false,
  },
  {
    id: 3,
    name: "Ultimate 3D Bluetooth Speaker",
    imgSrc: require( '../../static/images/product/product-1/product-1.jpg' ),
    oldPrice: "77.00",
    price: "23.00",
    link: "#",
    enableAddToCart: false,
    quantity: 0,
    totalQuantity: 46,
    isFavorite: false,
    checked: false,
    isComplete: false,
  },
  {
    id: 4,
    name: "Ultimate 3D Bluetooth Speaker",
    imgSrc: require( '../../static/images/product/product-1/product-2.jpg' ),
    oldPrice: "98.00",
    price: "89.00",
    link: "#",
    enableAddToCart: false,
    quantity: 0,
    totalQuantity: 2,
    isFavorite: false,
    checked: false,
    isComplete: false,
  },
  {
    id: 5,
    name: "Ultimate 3D Bluetooth Speaker",
    imgSrc: require( '../../static/images/product/product-1/product-2.jpg' ),
    oldPrice: "111.00",
    price: "3.00",
    link: "#",
    enableAddToCart: false,
    quantity: 0,
    totalQuantity: 57,
    isFavorite: false,
    checked: false,
    isComplete: false,
  },
  {
    id: 6,
    name: "Ultimate 3D Bluetooth Speaker",
    imgSrc: require( '../../static/images/product/product-1/product-2.jpg' ),
    oldPrice: "20.00",
    price: "49.00",
    link: "#",
    enableAddToCart: false,
    quantity: 0,
    totalQuantity: 10,
    isFavorite: false,
    checked: false,
    isComplete: false,
  },
]
export default ProductList;
